// <auto-generated />
using System;
using AgricultureApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgricultureApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260501060126_AddDiagnosticImages")]
    partial class AddDiagnosticImages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AgricultureApp.Models.Entities.Agriculteur", b =>
                {
                    b.Property<int>("idAgriculteur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idAgriculteur"));

                    b.Property<string>("Localisation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("idAgriculteur");

                    b.ToTable("Agriculteurs");
                });

            modelBuilder.Entity("AgricultureApp.Models.Entities.AvisProduit", b =>
                {
                    b.Property<int>("IdAvis")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAvis"));

                    b.Property<string>("Commentaire")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("DateAvis")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdProduit")
                        .HasColumnType("int");

                    b.Property<int?>("IdUtilisateur")
                        .HasColumnType("int");

                    b.Property<string>("NomAuteur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Note")
                        .HasColumnType("int");

                    b.Property<bool>("Verifie")
                        .HasColumnType("bit");

                    b.HasKey("IdAvis");

                    b.HasIndex("IdProduit");

                    b.ToTable("AvisProduits");
                });

            modelBuilder.Entity("AgricultureApp.Models.Entities.Commande", b =>
                {
                    b.Property<int>("IdCommande")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCommande"));

                    b.Property<string>("AdresseLivraison")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodePostalLivraison")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCommande")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateExpedition")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLivraison")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailClient")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("FraisLivraison")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("GouvernoratLivraison")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdAgriculteur")
                        .HasColumnType("int");

                    b.Property<int?>("IdUtilisateur")
                        .HasColumnType("int");

                    b.Property<string>("ModePaiement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomClient")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotesCommande")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroCommande")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("SousTotal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelephoneClient")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("VilleLivraison")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCommande");

                    b.HasIndex("NumeroCommande")
                        .IsUnique();

                    b.ToTable("Commandes");
                });

            modelBuilder.Entity("AgricultureApp.Models.Entities.DiagnosticAcrique", b =>
                {
                    b.Property<int>("IdDiagnostic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDiagnostic"));

                    b.Property<string>("Commentaire")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateDiagnostic")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ImageSatelliteId")
                        .HasColumnType("int");

                    b.Property<string>("NiveauRisque")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ParcelleId")
                        .HasColumnType("int");

                    b.Property<double?>("ScoreConfiance")
                        .HasColumnType("float");

                    b.Property<string>("TypeStress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdDiagnostic");

                    b.HasIndex("ImageSatelliteId");

                    b.HasIndex("ParcelleId");

                    b.ToTable("DiagnosticsAcriques");
                });

            modelBuilder.Entity("AgricultureApp.Models.Entities.DiagnosticImage", b =>
                {
                    b.Property<int>("IdDiagnostic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDiagnostic"));

                    b.Property<double>("Confiance")
                        .HasColumnType("float");

                    b.Property<DateTime>("DateDiagnostic")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EstSain")
                        .HasColumnType("bit");

                    b.Property<int?>("IdUtilisateur")
                        .HasColumnType("int");

                    b.Property<string>("MaladieDetectee")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NomFichier")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PlanteDetectee")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ProduitsRecommandes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdDiagnostic");

                    b.ToTable("DiagnosticsImages");
                });

            modelBuilder.Entity("AgricultureApp.Models.Entities.DonneeLocale", b =>
                {
                    b.Property<int>("IdLocal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLocal"));

                    b.Property<string>("ContenuJSON")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateSynchronisation")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Etat")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TypeObjet")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdLocal");

                    b.ToTable("DonneesLocales");
                });

            modelBuilder.Entity("AgricultureApp.Models.Entities.DonneesMeteo", b =>
                {
                    b.Property<int>("IdDonnee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDonnee"));

                    b.Property<DateTime>("DateHeure")
                        .HasColumnType("datetime2");

                    b.Property<string>("DirectionVent")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Humidite")
                        .HasColumnType("float");

                    b.Property<double>("Pluviometrie")
                        .HasColumnType("float");

                    b.Property<double>("Pression")
                        .HasColumnType("float");

                    b.Property<double>("RayonnementSolaire")
                        .HasColumnType("float");

                    b.Property<int?>("StationMeteoId")
                        .HasColumnType("int");

                    b.Property<double>("Temperature")
                        .HasColumnType("float");

                    b.Property<double>("VitesseVent")
                        .HasColumnType("float");

                    b.HasKey("IdDonnee");

                    b.HasIndex("DateHeure");

                    b.HasIndex("StationMeteoId");

                    b.ToTable("DonneesMeteo");
                });

            modelBuilder.Entity("AgricultureApp.Models.Entities.Ferme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgriculteurId")
                        .HasColumnType("int");

                    b.Property<string>("Couleur")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<string>("Delegation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Gouvernorat")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("RegionId")
                        .HasColumnType("int");

                    b.Property<string>("Secteur")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AgriculteurId");

                    b.HasIndex("RegionId");

                    b.ToTable("Fermes");
                });

            modelBuilder.Entity("AgricultureApp.Models.Entities.ImageSatellite", b =>
                {
                    b.Property<int>("IdImage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdImage"));

                    b.Property<DateTime>("DateCapture")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateImport")
                        .HasColumnType("datetime2");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Resolution")
                        .HasColumnType("float");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TypeImage")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UrlImage")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("IdImage");

                    b.ToTable("ImagesSatellite");
                });

            modelBuilder.Entity("AgricultureApp.Models.Entities.LigneCommande", b =>
                {
                    b.Property<int>("IdLigneCommande")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLigneCommande"));

                    b.Property<int>("IdCommande")
                        .HasColumnType("int");

                    b.Property<int>("IdProduit")
                        .HasColumnType("int");

                    b.Property<decimal>("PrixUnitaire")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.Property<decimal>("SousTotal")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("IdLigneCommande");

                    b.HasIndex("IdCommande");

                    b.HasIndex("IdProduit");

                    b.ToTable("LignesCommande");
                });

            modelBuilder.Entity("AgricultureApp.Models.Entities.LignePanier", b =>
                {
                    b.Property<int>("IdLignePanier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLignePanier"));

                    b.Property<DateTime>("DateAjout")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdPanier")
                        .HasColumnType("int");

                    b.Property<int>("IdProduit")
                        .HasColumnType("int");

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.HasKey("IdLignePanier");

                    b.HasIndex("IdPanier");

                    b.HasIndex("IdProduit");

                    b.ToTable("LignesPanier");
                });

            modelBuilder.Entity("AgricultureApp.Models.Entities.Panier", b =>
                {
                    b.Property<int>("IdPanier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPanier"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateMaj")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdUtilisateur")
                        .HasColumnType("int");

                    b.Property<string>("SessionId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdPanier");

                    b.HasIndex("IdUtilisateur");

                    b.HasIndex("SessionId");

                    b.ToTable("Paniers");
                });

            modelBuilder.Entity("AgricultureApp.Models.Entities.Parcelle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgriculteurId")
                        .HasColumnType("int");

                    b.Property<decimal?>("AltitudeMax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AltitudeMin")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AltitudeMoyenne")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ClassePente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Couleur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Culture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatePlantation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateRecolte")
                        .HasColumnType("datetime2");

                    b.Property<string>("Delegation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DerniereSynchronisation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EstSynchronise")
                        .HasColumnType("bit");

                    b.Property<string>("Exposition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FermeId")
                        .HasColumnType("int");

                    b.Property<string>("Geometrie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gouvernorat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(18, 15)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(18, 15)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PenteMoyenne")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("RegionId")
                        .HasColumnType("int");

                    b.Property<string>("Secteur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Surface")
                        .HasColumnType("decimal(10, 6)");

                    b.HasKey("Id");

                    b.HasIndex("AgriculteurId");

                    b.HasIndex("FermeId");

                    b.HasIndex("RegionId");

                    b.ToTable("Parcelles");
                });

            modelBuilder.Entity("AgricultureApp.Models.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categorie")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("AgricultureApp.Models.Entities.Produit", b =>
                {
                    b.Property<int>("IdProduit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProduit"));

                    b.Property<string>("Categorie")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CulturesCompatibles")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateAjout")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("EstActif")
                        .HasColumnType("bit");

                    b.Property<bool>("EstEnPromotion")
                        .HasColumnType("bit");

                    b.Property<string>("Fabricant")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatieresActives")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("NombreAvis")
                        .HasColumnType("int");

                    b.Property<double>("NoteMoyenne")
                        .HasColumnType("float");

                    b.Property<string>("NumeroAMM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Prix")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("PrixPromo")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("StockDisponible")
                        .HasColumnType("int");

                    b.Property<string>("Unite")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdProduit");

                    b.HasIndex("Categorie");

                    b.HasIndex("EstActif");

                    b.ToTable("Produits");
                });

            modelBuilder.Entity("AgricultureApp.Models.Entities.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("AgricultureApp.Models.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("AgricultureApp.Models.Entities.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("AgricultureApp.Models.Entities.StationMeteo", b =>
                {
                    b.Property<int>("IdStation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdStation"));

                    b.Property<string>("Fournisseur")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Localisation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TypeStation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdStation");

                    b.ToTable("StationsMeteo");
                });

            modelBuilder.Entity("AgricultureApp.Models.Entities.Synchronisation", b =>
                {
                    b.Property<int>("IdSync")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSync"));

                    b.Property<DateTime>("DateSync")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("NombreObjetsSync")
                        .HasColumnType("int");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UtilisateurId")
                        .HasColumnType("int");

                    b.HasKey("IdSync");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("Synchronisations");
                });

            modelBuilder.Entity("AgricultureApp.Models.Entities.UserPermission", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("UserPermissions");
                });

            modelBuilder.Entity("AgricultureApp.Models.Entities.UserRegionAccess", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RegionId");

                    b.HasIndex("RegionId");

                    b.ToTable("UserRegionAccesses");
                });

            modelBuilder.Entity("AgricultureApp.Models.Entities.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("AgricultureApp.Models.Entities.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AgriculteurId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("DerniereConnexion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("EstActif")
                        .HasColumnType("bit");

                    b.Property<string>("Localisation")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MotDePasseHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telephone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AgriculteurId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("AgricultureApp.Models.Entities.AvisProduit", b =>
                {
                    b.HasOne("AgricultureApp.Models.Entities.Produit", "Produit")
                        .WithMany("Avis")
                        .HasForeignKey("IdProduit")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("AgricultureApp.Models.Entities.DiagnosticAcrique", b =>
                {
                    b.HasOne("AgricultureApp.Models.Entities.ImageSatellite", "ImageSatellite")
                        .WithMany()
                        .HasForeignKey("ImageSatelliteId");

                    b.HasOne("AgricultureApp.Models.Entities.Parcelle", "Parcelle")
                        .WithMany()
                        .HasForeignKey("ParcelleId");

                    b.Navigation("ImageSatellite");

                    b.Navigation("Parcelle");
                });

            modelBuilder.Entity("AgricultureApp.Models.Entities.DonneesMeteo", b =>
                {
                    b.HasOne("AgricultureApp.Models.Entities.StationMeteo", "StationMeteo")
                        .WithMany("DonneesMeteo")
                        .HasForeignKey("StationMeteoId");

                    b.Navigation("StationMeteo");
                });

            modelBuilder.Entity("AgricultureApp.Models.Entities.Ferme", b =>
                {
                    b.HasOne("AgricultureApp.Models.Entities.Agriculteur", "Agriculteur")
                        .WithMany("Fermes")
                        .HasForeignKey("AgriculteurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgricultureApp.Models.Entities.Region", "Region")
                        .WithMany("Fermes")
                        .HasForeignKey("RegionId");

                    b.Navigation("Agriculteur");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("AgricultureApp.Models.Entities.LigneCommande", b =>
                {
                    b.HasOne("AgricultureApp.Models.Entities.Commande", "Commande")
                        .WithMany("Lignes")
                        .HasForeignKey("IdCommande")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgricultureApp.Models.Entities.Produit", "Produit")
                        .WithMany("LignesCommande")
                        .HasForeignKey("IdProduit")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commande");

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("AgricultureApp.Models.Entities.LignePanier", b =>
                {
                    b.HasOne("AgricultureApp.Models.Entities.Panier", "Panier")
                        .WithMany("Lignes")
                        .HasForeignKey("IdPanier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgricultureApp.Models.Entities.Produit", "Produit")
                        .WithMany("LignesPanier")
                        .HasForeignKey("IdProduit")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Panier");

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("AgricultureApp.Models.Entities.Parcelle", b =>
                {
                    b.HasOne("AgricultureApp.Models.Entities.Agriculteur", "Agriculteur")
                        .WithMany("Parcelles")
                        .HasForeignKey("AgriculteurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgricultureApp.Models.Entities.Ferme", "Ferme")
                        .WithMany("Parcelles")
                        .HasForeignKey("FermeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AgricultureApp.Models.Entities.Region", "Region")
                        .WithMany("Parcelles")
                        .HasForeignKey("RegionId");

                    b.Navigation("Agriculteur");

                    b.Navigation("Ferme");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("AgricultureApp.Models.Entities.RolePermission", b =>
                {
                    b.HasOne("AgricultureApp.Models.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgricultureApp.Models.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("AgricultureApp.Models.Entities.Synchronisation", b =>
                {
                    b.HasOne("AgricultureApp.Models.Entities.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("AgricultureApp.Models.Entities.UserPermission", b =>
                {
                    b.HasOne("AgricultureApp.Models.Entities.Permission", "Permission")
                        .WithMany("UserPermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgricultureApp.Models.Entities.Utilisateur", "User")
                        .WithMany("UserPermissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AgricultureApp.Models.Entities.UserRegionAccess", b =>
                {
                    b.HasOne("AgricultureApp.Models.Entities.Region", "Region")
                        .WithMany("UserRegionAccesses")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgricultureApp.Models.Entities.Utilisateur", "User")
                        .WithMany("RegionAccesses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AgricultureApp.Models.Entities.UserRole", b =>
                {
                    b.HasOne("AgricultureApp.Models.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgricultureApp.Models.Entities.Utilisateur", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AgricultureApp.Models.Entities.Utilisateur", b =>
                {
                    b.HasOne("AgricultureApp.Models.Entities.Agriculteur", "Agriculteur")
                        .WithMany()
                        .HasForeignKey("AgriculteurId");

                    b.Navigation("Agriculteur");
                });

            modelBuilder.Entity("AgricultureApp.Models.Entities.Agriculteur", b =>
                {
                    b.Navigation("Fermes");

                    b.Navigation("Parcelles");
                });

            modelBuilder.Entity("AgricultureApp.Models.Entities.Commande", b =>
                {
                    b.Navigation("Lignes");
                });

            modelBuilder.Entity("AgricultureApp.Models.Entities.Ferme", b =>
                {
                    b.Navigation("Parcelles");
                });

            modelBuilder.Entity("AgricultureApp.Models.Entities.Panier", b =>
                {
                    b.Navigation("Lignes");
                });

            modelBuilder.Entity("AgricultureApp.Models.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserPermissions");
                });

            modelBuilder.Entity("AgricultureApp.Models.Entities.Produit", b =>
                {
                    b.Navigation("Avis");

                    b.Navigation("LignesCommande");

                    b.Navigation("LignesPanier");
                });

            modelBuilder.Entity("AgricultureApp.Models.Entities.Region", b =>
                {
                    b.Navigation("Fermes");

                    b.Navigation("Parcelles");

                    b.Navigation("UserRegionAccesses");
                });

            modelBuilder.Entity("AgricultureApp.Models.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("AgricultureApp.Models.Entities.StationMeteo", b =>
                {
                    b.Navigation("DonneesMeteo");
                });

            modelBuilder.Entity("AgricultureApp.Models.Entities.Utilisateur", b =>
                {
                    b.Navigation("RegionAccesses");

                    b.Navigation("UserPermissions");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
