// <auto-generated />
using System;
using AgricultureApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgricultureApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260119091512_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AgricultureApp.Models.Entities.Agriculteur", b =>
                {
                    b.Property<int>("IdAgriculteur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAgriculteur"));

                    b.Property<string>("Localisation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdAgriculteur");

                    b.ToTable("Agriculteurs");
                });

            modelBuilder.Entity("AgricultureApp.Models.Entities.DiagnosticAcrique", b =>
                {
                    b.Property<int>("IdDiagnostic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDiagnostic"));

                    b.Property<string>("Commentaire")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateDiagnostic")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ImageSatelliteId")
                        .HasColumnType("int");

                    b.Property<string>("NiveauRisque")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ParcelleId")
                        .HasColumnType("int");

                    b.Property<double?>("ScoreConfiance")
                        .HasColumnType("float");

                    b.Property<string>("TypeStress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdDiagnostic");

                    b.HasIndex("ImageSatelliteId");

                    b.HasIndex("ParcelleId");

                    b.ToTable("DiagnosticsAcriques");
                });

            modelBuilder.Entity("AgricultureApp.Models.Entities.DonneeLocale", b =>
                {
                    b.Property<int>("IdLocal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLocal"));

                    b.Property<string>("ContenuJSON")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateSynchronisation")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Etat")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TypeObjet")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdLocal");

                    b.ToTable("DonneesLocales");
                });

            modelBuilder.Entity("AgricultureApp.Models.Entities.DonneesMeteo", b =>
                {
                    b.Property<int>("IdDonnee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDonnee"));

                    b.Property<DateTime>("DateHeure")
                        .HasColumnType("datetime2");

                    b.Property<string>("DirectionVent")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Humidite")
                        .HasColumnType("float");

                    b.Property<double>("Pluviometrie")
                        .HasColumnType("float");

                    b.Property<double>("Pression")
                        .HasColumnType("float");

                    b.Property<double>("RayonnementSolaire")
                        .HasColumnType("float");

                    b.Property<int?>("StationMeteoId")
                        .HasColumnType("int");

                    b.Property<double>("Temperature")
                        .HasColumnType("float");

                    b.Property<double>("VitesseVent")
                        .HasColumnType("float");

                    b.HasKey("IdDonnee");

                    b.HasIndex("DateHeure");

                    b.HasIndex("StationMeteoId");

                    b.ToTable("DonneesMeteo");
                });

            modelBuilder.Entity("AgricultureApp.Models.Entities.ImageSatellite", b =>
                {
                    b.Property<int>("IdImage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdImage"));

                    b.Property<DateTime>("DateCapture")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateImport")
                        .HasColumnType("datetime2");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Resolution")
                        .HasColumnType("float");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TypeImage")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UrlImage")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("IdImage");

                    b.ToTable("ImagesSatellite");
                });

            modelBuilder.Entity("AgricultureApp.Models.Entities.Parcelle", b =>
                {
                    b.Property<int>("IdParcelle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdParcelle"));

                    b.Property<int>("AgriculteurId")
                        .HasColumnType("int");

                    b.Property<double?>("AltitudeMoyenne")
                        .HasColumnType("float");

                    b.Property<string>("ContourJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<string>("EtatSynchronisation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double?>("PenteMoyenne")
                        .HasColumnType("float");

                    b.Property<double?>("Superficie")
                        .HasColumnType("float");

                    b.HasKey("IdParcelle");

                    b.HasIndex("AgriculteurId");

                    b.ToTable("Parcelles");
                });

            modelBuilder.Entity("AgricultureApp.Models.Entities.StationMeteo", b =>
                {
                    b.Property<int>("IdStation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdStation"));

                    b.Property<string>("Fournisseur")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Localisation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TypeStation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdStation");

                    b.ToTable("StationsMeteo");
                });

            modelBuilder.Entity("AgricultureApp.Models.Entities.Synchronisation", b =>
                {
                    b.Property<int>("IdSync")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSync"));

                    b.Property<DateTime>("DateSync")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("NombreObjetsSync")
                        .HasColumnType("int");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UtilisateurId")
                        .HasColumnType("int");

                    b.HasKey("IdSync");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("Synchronisations");
                });

            modelBuilder.Entity("AgricultureApp.Models.Entities.Utilisateur", b =>
                {
                    b.Property<int>("IdUtilisateur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUtilisateur"));

                    b.Property<DateTime>("DateInscription")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MotDePasseHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdUtilisateur");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("AgricultureApp.Models.Entities.DiagnosticAcrique", b =>
                {
                    b.HasOne("AgricultureApp.Models.Entities.ImageSatellite", "ImageSatellite")
                        .WithMany()
                        .HasForeignKey("ImageSatelliteId");

                    b.HasOne("AgricultureApp.Models.Entities.Parcelle", "Parcelle")
                        .WithMany()
                        .HasForeignKey("ParcelleId");

                    b.Navigation("ImageSatellite");

                    b.Navigation("Parcelle");
                });

            modelBuilder.Entity("AgricultureApp.Models.Entities.DonneesMeteo", b =>
                {
                    b.HasOne("AgricultureApp.Models.Entities.StationMeteo", "StationMeteo")
                        .WithMany("DonneesMeteo")
                        .HasForeignKey("StationMeteoId");

                    b.Navigation("StationMeteo");
                });

            modelBuilder.Entity("AgricultureApp.Models.Entities.Parcelle", b =>
                {
                    b.HasOne("AgricultureApp.Models.Entities.Agriculteur", "Agriculteur")
                        .WithMany("Parcelles")
                        .HasForeignKey("AgriculteurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agriculteur");
                });

            modelBuilder.Entity("AgricultureApp.Models.Entities.Synchronisation", b =>
                {
                    b.HasOne("AgricultureApp.Models.Entities.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("AgricultureApp.Models.Entities.Agriculteur", b =>
                {
                    b.Navigation("Parcelles");
                });

            modelBuilder.Entity("AgricultureApp.Models.Entities.StationMeteo", b =>
                {
                    b.Navigation("DonneesMeteo");
                });
#pragma warning restore 612, 618
        }
    }
}
